using System.ComponentModel.DataAnnotations;

namespace HelpDesk.Api.Models;

/// <summary>A note on a ticket — either written by a person or generated by the system on a status change.</summary>
public class TicketComment
{
    public int Id { get; set; }

    public int TicketId { get; set; }

    public Ticket? Ticket { get; set; }

    [Required, StringLength(80)]
    public string Author { get; set; } = string.Empty;

    [Required, StringLength(1000, MinimumLength = 2)]
    public string Body { get; set; } = string.Empty;

    /// <summary>System comments record the audit trail and cannot be deleted by users.</summary>
    public bool IsSystem { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
